### ISSUE TITLE
Auto-start after restart 

### ISSUE THREAD

**Issue by Tariqzm** [pyamsoft/home-button#7]
Thanks for the great app!

After the last update, the app won't auto start after a device restart.

Device: HTC U Ultra
OS Version: 8.0.0

**Comment by pyamsoft** [comment]
Yep, just noticed this myself.

Thanks for the report, I'll figure out the regression and push a fix out.

**Comment by pyamsoft** [comment]
I believe I've managed to fix the problem with in version 3.8.8

I have released it to the store so hopefully you will see the update in a few days if not hours.

**Comment by Tariqzm** [comment]
@pyamsoft thank you! 
Usually hours.
I'll report back to you once I receive the update.

**Comment by Tariqzm** [comment]
@pyamsoft Thanks, the issue has been resolved and Updated is now Updates as well! :grinning:

**Comment by pyamsoft** [comment]
Great to hear!

You caught me on the typo :P what can I say - I figure only the curious people would even look to begin with.

Thank you for your contribution to the project.
I will close this issue, please re-open it if you think something is not fully resolved.
